version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: maven:3.8.5-openjdk-11
    container_name: todo-app
    working_dir: /app
    volumes:
      - /Users/tw40/todo:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "7080:7080"
    depends_on:
      - db
    command: mvn spring-boot:run

  proxy:
    image: nginx:latest
    container_name: todo-proxy
    ports:
      - "70:80"
    volumes:
      - /Users/tw40/todo/volumes/web:/usr/share/nginx/html
      - /Users/tw40/todo/volumes/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  db-data:
