services:
  db:
    image: mysql:8.0
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"

  app:
    image: maven:3.8.5-openjdk-11
    container_name: todo-app
    working_dir: /app
    volumes:
      # ここを /shift/mytodo/volumes/app に修正しました
      - /Users/tw40/todo/shift/mytodo/volumes/app:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "7080:7080"
    command: mvn spring-boot:run

  proxy:
    image: nginx:latest
    container_name: todo-proxy
    ports:
      - "70:80"
    volumes:
      # Nginxも同様に深い階層を参照するように修正
      - /Users/tw40/todo/shift/mytodo/volumes/app/src/main/resources/static:/usr/share/nginx/html
      - /Users/tw40/todo/shift/volumes/nginx/conf.d:/etc/nginx/conf.d
