services:
  app:
    container_name: todo-app
    image: amazoncorretto:11
    volumes:
      - /Users/tw40/todo/mytodo/volumes/app:/app
    working_dir: /app
    ports:
      - "7080:7080"  # 70:7080 を削除してこれだけにします
    command: tail -f /dev/null
    depends_on:
      - db

  db:
    container_name: todo-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  proxy:
    image: nginx:latest
    ports:
      - "70:70"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  web:
    container_name: todo-web
    image: nginx:latest
    volumes:
      - /Users/tw40/todo/volumes/web:/usr/share/nginx/html
      - /Users/tw40/todo/volumes/nginx/conf.d:/etc/nginx/conf.d
    # ports:
    #   - "70:80"  # ここが proxy と衝突するのでコメントアウト（または削除）
    depends_on:
      - app
